name: easinginious

services:
  backend:
    image: easinginious:0.0.1
    volumes:
      - /var/www/INGInious/:/var/www/INGInious/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend_network
    depends_on:
      - db

  db:
    image: mongo:8.0.0-noble
    networks:
      - backend_network

volumes:
  easinginious_data:

networks:
  backend_network:
