name: easinginious-dev

services:
  backend:
    image: easinginious:0.0.1-dev
    build:
      context: .
      target: development
    command: >
      sh -c "poetry -C /app install --sync &&
             poetry -C /app run inginious-webapp"
    volumes:
      - .:/app
    ports:
      - 80:80

  db:
    ports:
      - 27017:27017
