name: easinginious-dev

services:
  backend:
    image: easinginious:0.0.1-dev
    build:
      context: .
      target: development
    command: >
      sh -c "poetry install --sync &&
             poetry run python $(poetry run which inginious-webapp)"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - INGINIOUS_WEBAPP_HOST=0.0.0.0
      - INGINIOUS_WEBAPP_PORT=8080
      - INGINIOUS_WEBAPP_CONFIG=/var/www/INGInious/configuration.yaml

  db:
    ports:
      - 27017:27017
