name: easinginious-dev

services:
  app:
    image: easinginious:0.9.2-dev
    pull_policy: never
    build:
      context: .
      target: development
    command: >
      sh -c "poetry run easinginious updatedb &&
             poetry run inginious-webapp"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          initial_sync: true
        - action: restart
          path: pyproject.toml
    ports:
      - 80:80

  db:
    ports:
      - 27017:27017
