name: easinginious-dev

services:
  backend:
    image: easinginious:0.0.1-dev
    build:
      context: .
      target: development
    command: >
      sh -c "poetry install --sync &&
             poetry run python $(poetry run which inginious-webapp)"
    volumes:
      - .:/app
    ports:
      - 8080:8080

  db:
    ports:
      - 27017:27017
