name: easinginious

services:
  backend:
    image: easinginious:0.0.1
    group_add:
      - ${INGINIOUS_GID:?Please set the group id of the inginious group}
      - ${DOCKER_GID:?Please set the group id of the docker group}
    volumes:
      - /var/www/INGInious/:/var/www/INGInious/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend_network
    depends_on:
      - db

  db:
    image: mongo:8.0.0-noble
    volumes:
      - easinginious_data:/data/db
    networks:
      - backend_network

volumes:
  easinginious_data:

networks:
  backend_network:
