name: easinginious

services:
  app:
    image: easinginious:0.9.1
    privileged: true
    volumes:
      - easinginious_docker_data:/var/lib/docker
    networks:
      - db_network
    depends_on:
      - db

  db:
    image: mongo:8.0.0-noble
    volumes:
      - easinginious_data:/data/db
    networks:
      - db_network

volumes:
  easinginious_data:
  easinginious_docker_data:

networks:
  db_network:
