name: easinginious-dev

services:
  app:
    image: easinginious:0.9.1-dev
    build:
      context: .
      target: development
    command: >
      sh -c "poetry sync &&
             poetry run inginious-webapp"
    volumes:
      - .:/app
    ports:
      - 80:80

  db:
    ports:
      - 27017:27017
